name: PHPCS (Drupal Coder)

on:
  push:
    branches: [ main, 1.x ]
  pull_request:

permissions:
  contents: write   # allow the workflow to push auto-fixes

jobs:
  phpcs:
    runs-on: ubuntu-latest

    env:
      COMPOSER_NO_INTERACTION: "1"
      COMPOSER_NO_AUDIT: "1"
      COMPOSER_PROCESS_TIMEOUT: "0"
      MODULE_PATH: "."   # scan the whole repo; change to subdir if you want

    steps:
      - name: Check out
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          coverage: none
          tools: composer

      - name: Cache Composer downloads
        uses: actions/cache@v4
        with:
          path: ~/.composer/cache
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install dev tools
        run: |
          composer install --no-progress --prefer-dist

      # Normalize only module/text files, skip workflow files and binaries.
      - name: Normalize text files (LF + UTF-8)
        run: |
          sudo apt-get update -y
          sudo apt-get install -y dos2unix
          set -euo pipefail
          export LC_ALL=C

          # Build a list of text-ish files in the repo we care about.
          # We explicitly skip the .github directory so we don't touch the workflow file itself.
          mapfile -t FILES < <(git ls-files \
            '*.php' '*.module' '*.inc' '*.install' '*.theme' '*.yml' '*.yaml' \
            ':(exclude).github/*')

          # Filter out anything that 'file' thinks is binary, then:
          #  - convert CRLF->LF
          #  - ensure UTF-8 (dropping illegal bytes to avoid iconv erroring the job)
          for f in "${FILES[@]}"; do
            # Skip if file disappeared (rare on PRs with renames)
            [ -f "$f" ] || continue

            enc=$(file -bi "$f" | awk -F'=' '{print tolower($NF)}')
            case "$enc" in
              *binary*) continue ;;
            esac

            dos2unix "$f" >/dev/null 2>&1 || true
            # Only run iconv if it's not already UTF-8 (or we can just normalize again anyway).
            iconv -f utf-8 -t utf-8 -c "$f" -o "${f}.tmp" && mv "${f}.tmp" "$f"
          done

      - name: Auto-fix with PHPCBF
        run: |
          vendor/bin/phpcbf \
            --standard=phpcs.xml.dist \
            --extensions=php,module,inc,install,test,theme,yml \
            "$MODULE_PATH" || true

      - name: Commit auto-fixes (if any)
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Apply PHPCBF auto-fixes"
          commit_user_name: "GitHub Actions"
          commit_user_email: "actions@github.com"
          file_pattern: |
            **/*.php
            **/*.module
            **/*.inc
            **/*.install
            **/*.theme
            **/*.yml
            **/*.yaml

      - name: Run PHPCS (report remaining)
        run: |
          vendor/bin/phpcs \
            --standard=phpcs.xml.dist \
            --extensions=php,module,inc,install,test,theme,yml \
            "$MODULE_PATH"

