name: PHPCS (Drupal Coder)

on:
  push:
    branches: [ main, 1.x ]
  pull_request:

permissions:
  contents: write

jobs:
  phpcs:
    runs-on: ubuntu-latest

    env:
      COMPOSER_NO_INTERACTION: "1"
      COMPOSER_NO_AUDIT: "1"
      COMPOSER_PROCESS_TIMEOUT: "0"
      MODULE_PATH: "."

    steps:
      - name: Check out
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          coverage: none
          tools: composer

      - name: Install dev tools
        run: composer install --no-progress --prefer-dist

      - name: Normalize text files
        run: |
          sudo apt-get update -y
          sudo apt-get install -y dos2unix
          find . -type f \( -name "*.php" -o -name "*.module" -o -name "*.inc" -o -name "*.install" -o -name "*.yml" -o -name "*.yaml" \) -print0 \
            | xargs -0 -I{} bash -lc 'dos2unix "{}" >/dev/null 2>&1 || true; iconv -f utf-8 -t utf-8 "{}" -o "{}".tmp && mv "{}".tmp "{}"'

      - name: Auto-fix with PHPCBF
        run: |
          vendor/bin/phpcbf \
            --standard=phpcs.xml.dist \
            --extensions=php,module,inc,install,test,theme,yml \
            "$MODULE_PATH" || true

      - name: Commit auto-fixes (if any)
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Apply PHPCBF auto-fixes"
          commit_user_name: "GitHub Actions"
          commit_user_email: "actions@github.com"
          file_pattern: |
            **/*.php
            **/*.module
            **/*.inc
            **/*.install
            **/*.theme
            **/*.yml
            **/*.yaml

      - name: Run PHPCS (report remaining)
        run: |
          vendor/bin/phpcs \
            --standard=phpcs.xml.dist \
            --extensions=php,module,inc,install,test,theme,yml \
            "$MODULE_PATH"

