name: PHPCS (Drupal Coder)

on:
  push:
  pull_request:

jobs:
  phpcs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          coverage: none
          tools: composer

      - name: Install dependencies
        run: composer install --no-progress --no-interaction

      # Try to find the module directory. Falls back to repo root.
      - name: Detect module path
        id: detect
        shell: bash
        run: |
          if [ -d web/modules/custom/simpleavs ]; then
            MP="web/modules/custom/simpleavs"
          elif [ -f simpleavs.info.yml ]; then
            MP="."
          else
            # best-effort: find any simpleavs.info.yml anywhere
            P=$(git ls-files '**/simpleavs.info.yml' | head -n1 || true)
            if [ -n "$P" ]; then MP="$(dirname "$P")"; else MP="."; fi
          fi
          echo "MODULE_PATH=$MP" | tee -a "$GITHUB_ENV"

      - name: Run PHPCS
        run: |
          echo "Scanning: $MODULE_PATH"
          vendor/bin/phpcs \
            --standard=phpcs.xml.dist \
            --extensions=php,module,inc,install,test,theme,yml \
            "$MODULE_PATH"

      # Optional: upload a text report as an artifact
      - name: PHPCS report (artifact)
        if: failure()
        run: |
          vendor/bin/phpcs \
            --standard=phpcs.xml.dist \
            --report=full \
            --report-file=phpcs-report.txt \
            --extensions=php,module,inc,install,test,theme,yml \
            "$MODULE_PATH" || true
        continue-on-error: true
      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: phpcs-report
          path: phpcs-report.txt

